### PR TITLE
No EOL conversion on .ini files

### PR DESCRIPTION
**Pull request by JenusL**
**Problem**
Most 3ds Max .ini files are encoded as UTF-16 LE. Git has no support for that encoding so Git commits them as binary, so they are not modified on commit.
But they are corrupted on checkout because Git still tries to do EOL conversion on them.

**Solution**
Don't do any EOL line conversion at all on .ini files. (explicitly treat them as binary)

**Bonus**
Added 3ds max 2021 preference files.

**Bugs found but not fixed in this PR**
I think all 3dsmax .cfg files is trying to copy Workspace1.se.ini from the wrong place so it never gets copied.
```
CommandLine=
        <rrLocalBin>rrCopy -oa "<rrPrefs>Workspace1.se.ini" "%LOCALAPPDATA%\Autodesk\3dsMax\%rrExeVersionMajor% - 64bit\ENU\en-US\UI\Workspaces\Workspace1.se.ini"
```
That should of course include the max version dir and be
```
CommandLine=
        <rrLocalBin>rrCopy -oa "<rrPrefs>%rrExeVersionMajor%\Workspace1.se.ini" "%LOCALAPPDATA%\Autodesk\3dsMax\%rrExeVersionMajor% - 64bit\ENU\en-US\UI\Workspaces\Workspace1.se.ini"
```
I didn't fix this because I don't even know what the workspace file is for and if it's needed.

### CODE REVIEW

**Comment by JenusL** [comment]
This bug was completely breaking our 3ds max rendering pipeline so you should probably release a 8.2.30a or something so others are not caught by this as well.

**Comment by h-schoenberger** [comment]
The global git preference on all our development machines is "Checkout as-is, Commit as-is". That is why the issue probably never happened before with the main repository. With this repo we could not force this setting on the machines of our customers, so we had to use the .gitattributes file. Which seems to have been wrong. I will compare the new files with the old files from the main repo just to be sure after merge.

Yes, we will release a "a" version in the next days.

Yes, you are right about the workspace.ini file. It was not required any more as Autodesk fixed the bug with the explorer window. 


thanks

**Comment by JenusL** [comment]
BTW, why couldn't you just use `-text` on all. So just keep the first line in .gitattributes and get rid of the rest to mimic how your internal git works. If any customer wants to change that it's up to them.

**Comment by h-schoenberger** [comment]
The setting "Checkout as-is, Commit as-is" is disabled by default.
Which means that everybody who pulls this repo has wrong files.

So you cannot use them for your local RR installation. 
And everyone who pushes changes to ask for a merge pushes wrong files.

**Comment by h-schoenberger** [comment]
Ah, I have just seem that the explanation is slightly wrong.
It was an explanation why we had to create the .gitattributes file.

The file types set in .gitattributes should ensure that 3rdparty pushes from Linux have the same line endings as all other lines in the file.

**Comment by JenusL** [comment]
> Ah, I have just seem that the explanation is slightly wrong.
> It was an explanation why we had to create the .gitattributes file.
> 
> The file types set in .gitattributes should ensure that 3rdparty pushes from Linux have the same line endings as all other lines in the file.

Ok I see. Well just be very careful with any encodings other than ASCII and UTF-8 because Git can't handle them very well.

**Comment by h-schoenberger** [comment]
>add 3dsmax 2021 ini files 
>change 3dsmax workspace inis to crlf
>convert kso_3dsmax.ini to crlf line endings
I have copied the old preference files and duplicated them for 2021.

The file kso_3dsmax.ini was not changed at all.

>don't do eol conversion on ini files
I have applied -text to the .gitattributes file

I changed <rrPrefs>Workspace1.se.ini for 3dsmax 2021+,  but not yet for the old files as it did not produce and error message. And I have seen that there had been only one file for all versions. This was changed to offer a file per version, but the change was not applied to the config files.

**Comment by h-schoenberger** [comment]
Hmm last message was not formatted right...



>    add 3dsmax 2021 ini files
 >   change 3dsmax workspace inis to crlf
>  convert kso_3dsmax.ini to crlf line endings

 I have copied the old preference files and duplicated them for 2021.
The file kso_3dsmax.ini was not changed as it was already crlf.



>don't do eol conversion on ini files

I have applied -text to the .gitattributes file

I changed Workspace1.se.ini for 3dsmax 2021+, but not yet for the old files as it did not produce and error message. And I have seen that there had been only one file for all versions. This was changed to offer a file per version, but the change was not applied to the config files.

**Comment by JenusL** [comment]
> I changed Workspace1.se.ini for 3dsmax 2021+, but not yet for the old files as it did not produce and error message. And I have seen that there had been only one file for all versions. This was changed to offer a file per version, but the change was not applied to the config files.

Yeah we don't get any errors either about the Workspace files... just this in the logs:
`S  7| CP|  Source file '/RoyalRender/render_apps/renderer_prefs/3dsmax/win_x64/Workspace1.se.ini' does not exist!`
If the workspace files aren't even needed anymore I rather see them gone than fixed :)

**Comment by JenusL** [comment]
We can close this right @h-schoenberger ?

**Pull request closed without merging**
